<?xml version="1.0"?>
<!-- <?php die(); ?> -->
<CONFIG>
    <REVERSE_PROXY>
        <ENABLED>false</ENABLED>
        <PURGE_COMMAND>sudo varnishadm "ban.url ."</PURGE_COMMAND>
    </REVERSE_PROXY>
	<PAGE type="file">
		<URIS>
			<PATTERN URI="/(.*)/" TTL="86400" KEY="UserGroup" />
		</URIS>
	</PAGE>
	<INVALIDATEON>
		<PAGE_PUBLISH>true</PAGE_PUBLISH>
		<FILE_PUBLISH>true</FILE_PUBLISH>
		<FILE_PROCESSVIEW>true</FILE_PROCESSVIEW>
		<CBLOCK_PUBLISH>true</CBLOCK_PUBLISH>
		<MAILING_PUBLISH>true</MAILING_PUBLISH>
		<PAGE_DELETE>true</PAGE_DELETE>
		<FILE_DELETE>true</FILE_DELETE>
		<CBLOCK_DELETE>true</CBLOCK_DELETE>
		<MAILING_DELETE>true</MAILING_DELETE>
		<TAG_DELETE>true</TAG_DELETE>
		<TAG_RENAME>true</TAG_RENAME>
		<COMMENT_ADD>false</COMMENT_ADD>
		<COMMENT_REMOVE>false</COMMENT_REMOVE>
		<COMMENT_CHANGE>false</COMMENT_CHANGE>
		<COMMENT_SETNOSPAM>false</COMMENT_SETNOSPAM>
		<COMMENT_SETSPAM>false</COMMENT_SETSPAM>
		<COMMENT_APPROVE>false</COMMENT_APPROVE>
		<COMMENT_UNAPPROVE>false</COMMENT_UNAPPROVE>
		<EXTENSION_INSTALL>true</EXTENSION_INSTALL>
		<EXTENSION_UNINSTALL>true</EXTENSION_UNINSTALL>
		<PERMISSION_CHANGE>true</PERMISSION_CHANGE>
		<PNAME_CHANGE>true</PNAME_CHANGE>
		<PROPERTY_CHANGE>true</PROPERTY_CHANGE>
		<TEMPLATE_CHANGE>true</TEMPLATE_CHANGE>
	</INVALIDATEON>
</CONFIG>